### ISSUE TITLE
Broken links to sdk documentation

### ISSUE THREAD

**Issue by lwsanty** [bblfsh/go-driver#48]
Links that refer to `sdk` `v3` are broken
https://godoc.org/github.com/bblfsh/sdk/v3/uast/transformer/positioner
https://github.com/bblfsh/go-driver/blob/274fb671efd2f274b8ff41707291d7c9e67b1d23/driver/normalizer/annotation.go#L34

However without `v3` everything's fine
https://godoc.org/github.com/bblfsh/sdk/v3/uast/transformer/positioner

**Comment by creachadair** [comment]
I think for the second link you probably meant https://godoc.org/github.com/bblfsh/sdk/uast/transformer/positioner?

In any case, godoc.org doesn't support modules yet, so we'll have to twiddle the paths manually for those packages. #49 will take care of the ones in this repo.
