### ISSUE TITLE
Missing positions in external import parts

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/go-driver#55]
Consider this code:

```
import "gopkg.in/src-d/go-git.v4"
```

Each leaf in the tree of type `uast:Identifier` has a Position, but it is not filled. The parent `uast:QualifiedIdentifier` has it filled, however.

**Comment by dennwc** [comment]
Yeah, I know where it comes from. The `uast:QualifiedIdentifier` is synthesized by splitting the import path, so we don't really have those positions from the parser. But it's easy to synthesize positions as well.

**Comment by vmarkovtsev** [comment]
cc @r0mainK

**Comment by r0mainK** [comment]
Very cool, will check if it changes anything when I can
